#!/usr/bin/sh
# (c) Travis Dowd
# (d) 6-9-2020
#
# Set keybindings similar to HHK layout for US key layout

# Set caps to control
setxkbmap -option ctrl:nocaps

# TODO: Set more keys, also have option to reset
# https://ictsolved.github.io/remap-key-in-linux/