#!/bin/sh
# shellcheck disable=SC2012
# shellcheck disable=SC2028

# Color Codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;36m'
PURPLE='\033[0;35m'
NC='\033[0m'

if [ ! -z $1 ]; then
	octal="$(stat -c "%a %n" "$1" | awk '{print $1}')"
	perms="$(ls -l "$1" | awk '{print $1}' | sed 's/\.//')"
	username="$(ls -l "$1" | awk '{print $3}')"
	groupname="$(ls -l "$1" | awk '{print $4}')"
	filename="$(ls -l "$1" | awk '{print $9}')"
	echo " "
	echo "File:  ${YELLOW}$filename ${NC}"
	echo "User:  ${GREEN}$username ${NC}"
	echo "Group: ${GREEN}$groupname ${NC}"
	echo "Octal: ${RED}$octal ${NC}"
	echo "r/w/x: ${RED}$perms ${NC}"
	echo "$perms" | grep -q 's' && echo "\t${PURPLE}[!]${NC} setuid flag is set"
	echo "$perms" | grep -l 'l' && echo "\t${PURPLE}[!]${NC} is a symbolic link"
	echo "$perms" | grep -l 't' && echo "\t${PURPLE}[!]${NC} has sticky bit permissions"
	echo " "
fi
