#!/bin/sh
# (c) Travis Dowd
# (d) 2-8-2021
#
# Nicely print out file permision stuff

# Color Codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;36m'
NC='\033[0m'

# Check what OS uuer is running
unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     machine=Linux;;
    Darwin*)    machine=Mac;;
    #CYGWIN*)    machine=Cygwin;;
    #MINGW*)     machine=MinGw;;
    #*)          machine="UNKNOWN:${unameOut}"
esac

if [ $machine = "Mac" ]
then
	octal="$(stat -f %A "$1")"
else
	octal="$(stat -c "%a %n" "$1" | awk '{print $1}')"
fi
perms="$(ls -l $1 | awk '{print $1}' | sed 's/\.//')"

username="$(ls -l $1 | awk '{print $3}')"
groupname="$(ls -l $1 | awk '{print $4}')"
filename="$(ls -l $1 | awk '{print $9}')"

echo " "
echo "File:  ${YELLOW}$filename ${NC}"
echo "User:  ${GREEN}$username ${NC}"
echo "Group: ${GREEN}$groupname ${NC}"
echo "r/w/x: ${RED}$perms ${NC}"
echo "Octal: ${RED}$octal ${NC}"
echo " "
